export const PROJECTS_DETAIL_DATA = [
 {
  id: 1,
  cat: "renovation",
  title: "LAKE TERRACE RESIDENCES",
  desc: "A comprehensive residential renovation within Lake Terrace Tower Cluster D, JLT — modernizing interiors, upgrading core systems, and delivering refined living spaces suited for contemporary Dubai lifestyle.",
  body: "This residential renovation project within the prestigious Lake Terrace Tower Cluster D, JLT, Dubai, involved a full-scale transformation of the apartment unit — from flooring and wall treatments to kitchen, bathroom, and MEP system overhauls — delivering a modern, high-quality living environment.",
  location: "LAKE TERRACE TOWER CLUSTER (D), JLT, DUBAI",
  image: "/images/apt2.jpeg",
  images: ["/images/apt5.jpeg", "/images/apt8.jpeg", "/images/apt10.jpeg", "/images/apt7.jpeg", "/images/apt3.jpeg","/images/apt11.jpeg","/images/apt12.jpeg","/images/apt9.jpeg","/images/apt1.jpeg","/images/apt2.jpeg"],
  imageLabels: ["BEFORE STATE","BEFORE STATE","BEFORE STATE", "DEMOLITION PHASE", "INTERIOR WORKS", "FINISHING PHASE","FINISHING PHASE", "FINAL HANDOVER", "FINAL HANDOVER", "FINAL HANDOVER"],
  objectives: [
    "Full interior refurbishment with modern finishes",
    "MEP systems upgrade — electrical, plumbing & HVAC",
    "Kitchen and bathroom remodeling",
    "Flooring replacement and premium wall treatments",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "Private Client",
    architect: "In-House Design Team",
    structural: "N/A",
    startDate: "Jan 2023",
    endDate: "Dec 2024",
  },
  highlights: [
    { icon: "🛠️", title: "Full Renovation",    desc: "End-to-end apartment overhaul"     },
    { icon: "✅", title: "100% Completed",      desc: "Successfully delivered on time"    },
    { icon: "🏙️", title: "Prime JLT Location", desc: "Lake Terrace Cluster D, Dubai"     },
  ],
  testimonial: {
    text: "The renovation was handled with great professionalism. Every detail was carefully executed, from the flooring to the finishing touches — the apartment looks and feels completely transformed.",
    name: "Private Client",
    role: "Apartment Owner, JLT Dubai",
    avatar: "https://i.pravatar.cc/80?img=22",
  },
  mapLocation: "Lake Terrace Tower Cluster D, Jumeirah Lake Towers (JLT), Dubai — close to JLT Metro Station and major amenities.",
},
  {
  id: 2,
  cat: "construction",
  title: "LIV MARINA MEDIA WALL",
  desc: "A precision-crafted media wall installation delivering a seamless entertainment focal point for a premium Marina residence.",
  body: "A bespoke media wall was designed and installed at Liv Residence Marina, combining clean structural joinery with integrated cable management and a refined finish — creating a striking centerpiece for modern living.",
  location: "LIV RESIDENCE, MARINA, DUBAI",
  image: "/images/apart2.jpeg",
  images: ["/images/wall1.jpeg", "/images/wall2.jpeg", "/images/wall3.jpeg", "/images/wall4.jpeg"],
  imageLabels: ["BEFORE STATE", "FRAMING PHASE",  "FINISHING", "FINAL LOOK"],
  objectives: [
    "Custom media wall design and fabrication",
    "Integrated cable and wire management",
    "Premium finish with modern materials",
    "Seamless TV and entertainment unit installation",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "Private Client",
    architect: "In-House Design Team",
    structural: "N/A",
    startDate: "Jan 2025",
    endDate: "Feb 2025",
  },
  highlights: [
    { icon: "🖥️", title: "Media Wall",       desc: "Custom built entertainment unit" },
    { icon: "✅", title: "100% Completed",    desc: "Delivered on time"               },
    { icon: "🏙️", title: "Prime Marina",     desc: "Liv Residence, Dubai Marina"     },
  ],
  testimonial: {
    text: "The media wall completely transformed the living space. The craftsmanship and attention to detail were outstanding — exactly what we envisioned for our Marina apartment.",
    name: "Rishab Sharma",
    role: "Apartment Owner, Liv Residence Marina",
    avatar: "https://i.pravatar.cc/80?img=33",
  },
  mapLocation: "Liv Residence, Dubai Marina — Waterfront living with direct Marina Walk access.",
},
  {
  id: 3,
  cat: "renovation",
  title: "LAKE TERRACE SUITE",
  desc: "A refined single-room renovation within Lake Terrace Tower Cluster D, JLT — transforming a compact space with modern finishes and smart design.",
  body: "This single-room renovation at Lake Terrace Tower Cluster D, JLT involved a complete interior overhaul — fresh wall treatments, flooring upgrade, and modern fixtures delivering a clean, contemporary living space.",
  location: "LAKE TERRACE TOWER CLUSTER (D), JLT, DUBAI",
  image: "/images/room2.jpeg",
  images: ["/images/room1.jpeg", "/images/room2.jpeg"],
  imageLabels: ["BEFORE", "FINAL LOOK"],
  objectives: [
    "Single room complete interior renovation",
    "Flooring replacement with modern finish",
    "Wall treatment and fresh paintwork",
    "Fixtures and fittings upgrade",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "Private Client",
    architect: "In-House Design Team",
    structural: "N/A",
    startDate: "Jan 2025",
    endDate: "Mar 2025",
  },
  highlights: [
    { icon: "🛠️", title: "Room Renovation", desc: "Full single room overhaul"      },
    { icon: "✅", title: "100% Completed",   desc: "Delivered on time"              },
    { icon: "🏙️", title: "Prime JLT",       desc: "Lake Terrace Cluster D, Dubai"  },
  ],
  testimonial: {
    text: "The room was completely transformed. Clean work, great attention to detail and delivered right on time.",
    name: "Dipti Singh",
    role: "Apartment Owner, JLT Dubai",
    avatar: "https://i.pravatar.cc/80?img=44",
  },
  mapLocation: "Lake Terrace Tower Cluster D, Jumeirah Lake Towers (JLT), Dubai — close to JLT Metro Station and major amenities.",
},
 {
  id: 4,
  cat: "construction",
  title: "LIV 27 BARBERSHOP",
  desc: "A full-scale barbershop construction and interior fit-out at Media City — designed and built from scratch with a modern, premium aesthetic.",
  body: "Liv 27 Barbershop at Media City was built entirely from the ground up — covering spatial planning, joinery, lighting design, plumbing, electrical works, and complete interior fit-out to deliver a fully operational premium barbershop.",
  location: "LIV 27, MEDIA CITY, DUBAI",
  image: "/images/bar4.jpeg",
  images: ["/images/bar3.jpeg", "/images/bar2.jpeg", "/images/bar4.jpeg", "/images/bar5.jpeg", "/images/bar6.jpeg","/images/bar7.jpeg","/images/bar8.jpeg","/images/bar9.jpeg","/images/bar1.jpeg"],
  imageLabels: ["BARBER STATION", "WAITING AREA", "RECEPTION DESK", "LIGHTING SETUP", "MIRROR WALL", "FLOORING DETAIL", "CEILING WORK", "RETAIL SHELF", "FINAL LOOK"],
  objectives: [
    "Full barbershop design and construction from scratch",
    "Custom joinery and furniture fabrication",
    "Electrical, plumbing and HVAC installation",
    "Premium interior fit-out and finishing",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "Liv 27",
    architect: "In-House Design Team",
    structural: "In-House Team",
    startDate: "Mar 2024",
    endDate: "Jun 2025",
  },
  highlights: [
    { icon: "✂️", title: "Barbershop Build",  desc: "Full fit-out from scratch"       },
    { icon: "✅", title: "100% Completed",     desc: "Delivered on time"               },
    { icon: "🏙️", title: "Media City Dubai",  desc: "Liv 27, prime commercial location"},
  ],
  testimonial: {
    text: "From empty shell to fully operational barbershop — the team handled every detail with precision. The space looks exactly how we imagined it, if not better.",
    name: "Jabar Bhallli",
    role: "Owner, Liv 27 Barbershop",
    avatar: "https://i.pravatar.cc/80?img=55",
  },
  mapLocation: "Liv 27, Media City, Dubai — Prime commercial hub with high footfall and easy access.",
},
  {
  id: 5,
  cat: "maintenance",
  title: "LVM CEILING LED INSTALL",
  desc: "Professional ceiling hanging LED lights installation across a premium performance car rental showroom in Al Quoz — enhancing ambiance and vehicle display lighting.",
  body: "A complete ceiling LED lighting solution was designed and installed at LVM Performance Car Rental, Al Quoz — covering hanging LED fixtures, wiring, and finishing to elevate the showroom's premium look and feel.",
  location: "AL QUOZ, LVM PERFORMANCE CAR RENTAL L.L.C, DUBAI",
  image: "/images/showroom2.jpeg",
  images: ["/images/showroom2.jpeg", "/images/showroom3.jpeg", "/images/showroom1.jpeg"],
imageLabels: ["SHOWROOM VIEW", "CEILING DETAIL", "FINAL LOOK"],
  objectives: [
    "Ceiling hanging LED lights full installation",
    "Custom wiring and electrical fitting",
    "Showroom ambiance and display lighting",
    "Clean finish with concealed cable management",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "LVM Performance Car Rental L.L.C",
    architect: "In-House Design Team",
    structural: "N/A",
    startDate: "Jan 2025",
    endDate: "Dec 2025",
  },
  highlights: [
    { icon: "💡", title: "LED Lighting",     desc: "Full ceiling LED installation"     },
    { icon: "✅", title: "100% Completed",   desc: "Delivered on time"                 },
    { icon: "🚗", title: "Car Showroom",     desc: "LVM Performance, Al Quoz Dubai"    },
  ],
 testimonial: {
  text: "The LED installation completely changed the feel of our showroom. The lighting highlights every car perfectly — professional work from start to finish.",
  name: "Khalid Al Mansoori",
  role: "Showroom Manager, LVM Performance Car Rental L.L.C",
  avatar: "https://i.pravatar.cc/80?img=12",
},
  mapLocation: "Al Quoz, Dubai — LVM Performance Car Rental L.L.C, industrial hub with easy Sheikh Zayed Road access.",
},

  {
  id: 6,
  cat: "construction",
  title: "GOLD CREST VIEW 2 — JLT",
  desc: "Residential construction and fitout works at Gold Crest View 2, Cluster J, Jumeirah Lake Towers — delivering premium living spaces in the heart of Dubai.",
  body: "A full-scale residential construction and interior fitout project undertaken at Gold Crest View 2, JLT Cluster J. Works included structural upgrades, flooring, ceiling, MEP installations, and finishing — tailored to meet the high standards of JLT's premium residential community.",
  location: "GOLD CREST VIEW 2, CLUSTER J, JLT, DUBAI",
  image: "/images/apt2-3.jpeg",
  images: [
    "/images/apt2-1.jpeg",
    "/images/apt2-12.jpeg",
    "/images/apt2-11.jpeg",
    "/images/apt2-10.jpeg",
    "/images/apt2-9.jpeg",
    "/images/apt2-8.jpeg",
    "/images/apt2-7.jpeg",
    "/images/apt2-6.jpeg",
    "/images/apt2-5.jpeg",
    "/images/apt2-4.jpeg",
    "/images/apt2-2.jpeg",
    "/images/apt2-3.jpeg",
  ],
  imageLabels: [
    "DEMOLITION PHASE",
    "MASTER BATHROOM",
    "MASTER BEDROOM",
    "BEDROOM — TV WALL",
    "BEDROOM — WARDROBE",
    "GUEST BEDROOM",
    "MODULAR KITCHEN",
    "ENTRANCE CORRIDOR",
    "LIVING AREA — MARBLE WALL",
    "MARBLE FEATURE INSTALLATION",
    "LIVING & DINING",
    "OPEN PLAN VIEW",
  ],
  objectives: [
    "Full residential fitout and finishing works",
    "MEP installations and electrical fitting",
    "Flooring, ceiling, and wall treatments",
    "Premium handover as per client specs",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "Private Client — JLT",
    architect: "In-House Design Team",
    structural: "N/A",
    startDate: "Aug 2025",
    endDate: "Dec 2025",
  },
  highlights: [
    { icon: "🏗️", title: "Construction",   desc: "Full fitout & finishing"       },
    { icon: "✅", title: "100% Completed", desc: "Delivered on time"             },
    { icon: "🏙️", title: "JLT Dubai",      desc: "Gold Crest View 2, Cluster J" },
  ],
  testimonial: {
    text: "The team delivered exceptional quality work at our JLT apartment. Every detail was handled professionally — from MEP to the final finishing touches.",
    name: "Ahmed Al Farsi",
    role: "Property Owner, JLT Dubai",
    avatar: "https://i.pravatar.cc/80?img=15",
  },
  mapLocation: "Gold Crest View 2, Cluster J, Jumeirah Lake Towers (JLT), Dubai — situated along Sheikh Zayed Road with direct Metro access.",
},
  {
  id: 7,
  cat: "maintenance",
  title: "LIV 27 BARBER SHOP — AL BARSHA",
  desc: "Complete fitout and interior construction of a premium barber shop at Liv 27, Al Barsha 1, Dubai — delivering a sleek, modern grooming space from scratch.",
  body: "A full barber shop fitout was carried out at Liv 27, Al Barsha 1, Dubai. The project covered complete interior construction including custom barber stations, plumbing, electrical works, wall cladding, flooring, ceiling works, and all finishing — resulting in a premium modern grooming space ready for operations.",
  location: "LIV 27, AL BARSHA 1, DUBAI",
  image: "/images/barber2-1.jpeg",
images: [
    "/images/barber2-2.jpeg",
    "/images/barber2-9.jpeg",
    "/images/barber2-8.jpeg",
    "/images/barber2-7.jpeg",
    "/images/barber2-6.jpeg",
    "/images/barber2-5.jpeg",
    "/images/barber2-4.jpeg",
    "/images/barber2-3.jpeg",
    "/images/barber2-1.jpeg",
  ],
  imageLabels: [
    "BRAND WALL",
    "OPTICAL ILLUSION CORRIDOR",
    "CORRIDOR ENTRANCE",
    "BARBER STATIONS",
    "BARBER FLOOR VIEW",
    "PRODUCT DISPLAY — IVORY STAMP",
    "RECEPTION COUNTER",
    "LAVAZZA COFFEE BAR",
    "FULL FLOOR VIEW",
  ],
  objectives: [
    "Full interior fitout from bare shell",
    "Custom barber stations and seating",
    "Electrical, plumbing and MEP works",
    "Wall cladding, flooring and ceiling finishing",
    "Lighting design and signage installation",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "Private Client — Al Barsha 1",
    architect: "In-House Design Team",
    structural: "N/A",
    startDate: "Nov 2025",
    endDate: "Apr 2025",
  },
  highlights: [
    { icon: "💈", title: "Barber Shop",      desc: "Premium grooming fitout"      },
    { icon: "🔧", title: "Full Fitout",      desc: "MEP, flooring & finishing"     },
    { icon: "✅", title: "100% Completed",   desc: "Delivered on time"             },
  ],
  testimonial: {
    text: "The team turned an empty shell into a fully finished barber shop in no time. Clean work, great attention to detail — our customers love the space.",
    name: "Bilal Hassan",
    role: "Shop Owner, Liv 27 Al Barsha 1",
    avatar: "https://i.pravatar.cc/80?img=8",
  },
  mapLocation: "Liv 27, Al Barsha 1, Dubai — centrally located near Mall of the Emirates with easy road access.",
},
 {
  id: 8,
  cat: "construction", // As per your request
  title: "TKMMAFIT WOODEN DISPLAY",
  desc: "High-end custom woodwork and display cabinet construction for a premier fitness facility.",
  body: "This project involved the precision construction of bespoke wooden display units. From material selection to the final polish, we ensured every cabinet reflects the premium branding of TKMMAFIT, blending durability with a sleek modern aesthetic.",
  location: "TKMMAFIT, AL BARSHA, DUBAI",
  image: "/images/fitout.jpeg",
  images: ["/images/fitout.jpeg"],
  imageLabels: ["DETAIL FINISH"],
  objectives: [
    "Structural wood framing",
    "Glass & lighting integration",
    "On-site installation & leveling",
    "Anti-scratch finishing",
  ],
  stats: { area: "1.2K sqft", floors: "1", value: "Custom", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "TKMMAFIT Dubai",
    architect: "IVORY Internal Team",
    structural: "Joinery Specialists",
    startDate: "Jan 2026",
    endDate: "Jan 2026",
  },
  highlights: [
    { icon: "🏗️", title: "Solid Build", desc: "Reinforced wood structure" },
    { icon: "✨", title: "Premium Finish", desc: "Custom stain and polish" },
    { icon: "📍", title: "Al Barsha", desc: "Prime Dubai Location" },
  ],
  testimonial: {
    text: "The construction quality of these display cabinets is exceptional. IVORY delivered exactly what we needed for our retail section.",
    name: "TKMMAFIT Management",
    role: "Omar Al-Rashid",
    avatar: "https://i.pravatar.cc/80?img=12",
  },
  mapLocation: "TKMMAFIT, Al Barsha, Dubai — conveniently located near Mall of the Emirates with easy access from Sheikh Zayed Road.",
},
  {
    id: 9, // Naya project ID
    cat: "maintenance",
    title: "AL BARARI LUXURY POOL CARE",
    desc: "Comprehensive pool cleaning and chemical balancing for a high-end villa in Al Barari.",
    body: "Professional maintenance service ensuring crystal clear water and optimal filtration. We handle everything from debris removal to pH stabilization, maintaining the aesthetic and hygiene standards of Dubai's greenest community.",
    location: "AL BARARI, DUBAI",
    image: "/images/pool1.jpeg", // Isse replace kar lena
    images: ["/images/pool1.jpeg", "/images/pool2.jpeg", "/images/pool3.jpeg", "/images/pool4.jpeg"],
    imageLabels: ["POOL VIEW", "FILTRATION CHECK", "CHEMICAL BALANCE", "DECK MAINTENANCE"],
    objectives: [
      "Surface skimming and vacuuming",
      "Filter backwash and cleaning",
      "Chemical level testing & adjustment",
      "Tile and deck pressure washing",
    ],
    stats: { area: "800 sqft", type: "Infinity", frequency: "Weekly", completion: "Ongoing" },
    status: {
      phase: "MAINTENANCE MODE",
      progress: 100,
      client: "Private Villa Owner",
      contractor: "IVORY Fit-Out & Services",
      startDate: "March 2026",
      endDate: "Recurring",
    },
    highlights: [
      { icon: "💧", title: "Crystal Clear", desc: "Premium water quality" },
      { icon: "🧪", title: "pH Balanced", desc: "Safe swimming levels" },
      { icon: "🌿", title: "Eco-Friendly", desc: "Safe for Al Barari greenery" },
    ],
    testimonial: {
      text: "Our pool has never looked better. The team is punctual and very thorough with the cleaning process.",
      name: "Villa Resident",
      role: "Homeowner",
      avatar: "https://i.pravatar.cc/80?img=32",
    },
    mapLocation: "Al Barari, Dubai — Exclusive botanical community with premium residential pool services.",
}
];
