export const PROJECTS_DETAIL_DATA = [
 {
  id: 1,
  cat: "renovation",
  title: "LAKE TERRACE RESIDENCES",
  desc: "A comprehensive residential renovation within Lake Terrace Tower Cluster D, JLT — modernizing interiors, upgrading core systems, and delivering refined living spaces suited for contemporary Dubai lifestyle.",
  body: "This residential renovation project within the prestigious Lake Terrace Tower Cluster D, JLT, Dubai, involved a full-scale transformation of the apartment unit — from flooring and wall treatments to kitchen, bathroom, and MEP system overhauls — delivering a modern, high-quality living environment.",
  location: "LAKE TERRACE TOWER CLUSTER (D), JLT, DUBAI",
  image: "/images/apt2.jpeg",
  images: ["/images/apt5.jpeg", "/images/apt8.jpeg", "/images/apt10.jpeg", "/images/apt7.jpeg", "/images/apt3.jpeg","/images/apt11.jpeg","/images/apt12.jpeg","/images/apt9.jpeg","/images/apt1.jpeg","/images/apt2.jpeg"],
  imageLabels: ["BEFORE STATE","BEFORE STATE","BEFORE STATE", "DEMOLITION PHASE", "INTERIOR WORKS", "FINISHING PHASE","FINISHING PHASE", "FINAL HANDOVER", "FINAL HANDOVER", "FINAL HANDOVER"],
  objectives: [
    "Full interior refurbishment with modern finishes",
    "MEP systems upgrade — electrical, plumbing & HVAC",
    "Kitchen and bathroom remodeling",
    "Flooring replacement and premium wall treatments",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "Private Client",
    architect: "In-House Design Team",
    structural: "N/A",
    startDate: "Jan 2023",
    endDate: "Dec 2024",
  },
  highlights: [
    { icon: "🛠️", title: "Full Renovation",    desc: "End-to-end apartment overhaul"     },
    { icon: "✅", title: "100% Completed",      desc: "Successfully delivered on time"    },
    { icon: "🏙️", title: "Prime JLT Location", desc: "Lake Terrace Cluster D, Dubai"     },
  ],
  testimonial: {
    text: "The renovation was handled with great professionalism. Every detail was carefully executed, from the flooring to the finishing touches — the apartment looks and feels completely transformed.",
    name: "Private Client",
    role: "Apartment Owner, JLT Dubai",
    avatar: "https://i.pravatar.cc/80?img=22",
  },
  mapLocation: "Lake Terrace Tower Cluster D, Jumeirah Lake Towers (JLT), Dubai — close to JLT Metro Station and major amenities.",
},
  {
  id: 2,
  cat: "construction",
  title: "LIV MARINA MEDIA WALL",
  desc: "A precision-crafted media wall installation delivering a seamless entertainment focal point for a premium Marina residence.",
  body: "A bespoke media wall was designed and installed at Liv Residence Marina, combining clean structural joinery with integrated cable management and a refined finish — creating a striking centerpiece for modern living.",
  location: "LIV RESIDENCE, MARINA, DUBAI",
  image: "/images/apart2.jpeg",
  images: ["/images/wall1.jpeg", "/images/wall2.jpeg", "/images/wall3.jpeg", "/images/wall4.jpeg"],
  imageLabels: ["BEFORE STATE", "FRAMING PHASE",  "FINISHING", "FINAL LOOK"],
  objectives: [
    "Custom media wall design and fabrication",
    "Integrated cable and wire management",
    "Premium finish with modern materials",
    "Seamless TV and entertainment unit installation",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "Private Client",
    architect: "In-House Design Team",
    structural: "N/A",
    startDate: "Jan 2025",
    endDate: "Feb 2025",
  },
  highlights: [
    { icon: "🖥️", title: "Media Wall",       desc: "Custom built entertainment unit" },
    { icon: "✅", title: "100% Completed",    desc: "Delivered on time"               },
    { icon: "🏙️", title: "Prime Marina",     desc: "Liv Residence, Dubai Marina"     },
  ],
  testimonial: {
    text: "The media wall completely transformed the living space. The craftsmanship and attention to detail were outstanding — exactly what we envisioned for our Marina apartment.",
    name: "Rishab Sharma",
    role: "Apartment Owner, Liv Residence Marina",
    avatar: "https://i.pravatar.cc/80?img=33",
  },
  mapLocation: "Liv Residence, Dubai Marina — Waterfront living with direct Marina Walk access.",
},
  {
  id: 3,
  cat: "renovation",
  title: "LAKE TERRACE SUITE",
  desc: "A refined single-room renovation within Lake Terrace Tower Cluster D, JLT — transforming a compact space with modern finishes and smart design.",
  body: "This single-room renovation at Lake Terrace Tower Cluster D, JLT involved a complete interior overhaul — fresh wall treatments, flooring upgrade, and modern fixtures delivering a clean, contemporary living space.",
  location: "LAKE TERRACE TOWER CLUSTER (D), JLT, DUBAI",
  image: "/images/room2.jpeg",
  images: ["/images/room1.jpeg", "/images/room2.jpeg"],
  imageLabels: ["BEFORE", "FINAL LOOK"],
  objectives: [
    "Single room complete interior renovation",
    "Flooring replacement with modern finish",
    "Wall treatment and fresh paintwork",
    "Fixtures and fittings upgrade",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "Private Client",
    architect: "In-House Design Team",
    structural: "N/A",
    startDate: "Jan 2025",
    endDate: "Mar 2025",
  },
  highlights: [
    { icon: "🛠️", title: "Room Renovation", desc: "Full single room overhaul"      },
    { icon: "✅", title: "100% Completed",   desc: "Delivered on time"              },
    { icon: "🏙️", title: "Prime JLT",       desc: "Lake Terrace Cluster D, Dubai"  },
  ],
  testimonial: {
    text: "The room was completely transformed. Clean work, great attention to detail and delivered right on time.",
    name: "Dipti Singh",
    role: "Apartment Owner, JLT Dubai",
    avatar: "https://i.pravatar.cc/80?img=44",
  },
  mapLocation: "Lake Terrace Tower Cluster D, Jumeirah Lake Towers (JLT), Dubai — close to JLT Metro Station and major amenities.",
},
 {
  id: 4,
  cat: "construction",
  title: "LIV 27 BARBERSHOP",
  desc: "A full-scale barbershop construction and interior fit-out at Media City — designed and built from scratch with a modern, premium aesthetic.",
  body: "Liv 27 Barbershop at Media City was built entirely from the ground up — covering spatial planning, joinery, lighting design, plumbing, electrical works, and complete interior fit-out to deliver a fully operational premium barbershop.",
  location: "LIV 27, MEDIA CITY, DUBAI",
  image: "/images/bar4.jpeg",
  images: ["/images/bar3.jpeg", "/images/bar2.jpeg", "/images/bar4.jpeg", "/images/bar5.jpeg", "/images/bar6.jpeg","/images/bar7.jpeg","/images/bar8.jpeg","/images/bar9.jpeg","/images/bar1.jpeg"],
  imageLabels: ["BARBER STATION", "WAITING AREA", "RECEPTION DESK", "LIGHTING SETUP", "MIRROR WALL", "FLOORING DETAIL", "CEILING WORK", "RETAIL SHELF", "FINAL LOOK"],
  objectives: [
    "Full barbershop design and construction from scratch",
    "Custom joinery and furniture fabrication",
    "Electrical, plumbing and HVAC installation",
    "Premium interior fit-out and finishing",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "Liv 27",
    architect: "In-House Design Team",
    structural: "In-House Team",
    startDate: "Mar 2024",
    endDate: "Jun 2025",
  },
  highlights: [
    { icon: "✂️", title: "Barbershop Build",  desc: "Full fit-out from scratch"       },
    { icon: "✅", title: "100% Completed",     desc: "Delivered on time"               },
    { icon: "🏙️", title: "Media City Dubai",  desc: "Liv 27, prime commercial location"},
  ],
  testimonial: {
    text: "From empty shell to fully operational barbershop — the team handled every detail with precision. The space looks exactly how we imagined it, if not better.",
    name: "Jabar Bhallli",
    role: "Owner, Liv 27 Barbershop",
    avatar: "https://i.pravatar.cc/80?img=55",
  },
  mapLocation: "Liv 27, Media City, Dubai — Prime commercial hub with high footfall and easy access.",
},
  {
  id: 5,
  cat: "maintenance",
  title: "LVM CEILING LED INSTALL",
  desc: "Professional ceiling hanging LED lights installation across a premium performance car rental showroom in Al Quoz — enhancing ambiance and vehicle display lighting.",
  body: "A complete ceiling LED lighting solution was designed and installed at LVM Performance Car Rental, Al Quoz — covering hanging LED fixtures, wiring, and finishing to elevate the showroom's premium look and feel.",
  location: "AL QUOZ, LVM PERFORMANCE CAR RENTAL L.L.C, DUBAI",
  image: "/images/gag5.jpeg",
  images: ["/images/showroom2.jpeg", "/images/showroom3.jpeg", "/images/showroom1.jpeg"],
imageLabels: ["SHOWROOM VIEW", "CEILING DETAIL", "FINAL LOOK"],
  objectives: [
    "Ceiling hanging LED lights full installation",
    "Custom wiring and electrical fitting",
    "Showroom ambiance and display lighting",
    "Clean finish with concealed cable management",
  ],
  stats: { area: "TBD", floors: "1", value: "AED —", completion: "100" },
  status: {
    phase: "COMPLETED",
    progress: 100,
    client: "LVM Performance Car Rental L.L.C",
    architect: "In-House Design Team",
    structural: "N/A",
    startDate: "Jan 2025",
    endDate: "Dec 2025",
  },
  highlights: [
    { icon: "💡", title: "LED Lighting",     desc: "Full ceiling LED installation"     },
    { icon: "✅", title: "100% Completed",   desc: "Delivered on time"                 },
    { icon: "🚗", title: "Car Showroom",     desc: "LVM Performance, Al Quoz Dubai"    },
  ],
  testimonial: {
    text: "The LED installation completely changed the feel of our showroom. The lighting highlights every car perfectly — professional work from start to finish.",
    name: "Showroom Manager",
    role: "LVM Performance Car Rental L.L.C",
    avatar: "https://i.pravatar.cc/80?img=66",
  },
  mapLocation: "Al Quoz, Dubai — LVM Performance Car Rental L.L.C, industrial hub with easy Sheikh Zayed Road access.",
},

  {
    id: 6,
    cat: "renovation",
    title: "SKYLINE LOFTS",
    desc: "Transformation of an old textile factory into 120 premium residential loft apartments.",
    body: "Industrial heritage meets contemporary living — exposed brick, soaring ceilings, and open floor plans breathe new life into a century-old factory in the heart of Brooklyn.",
    location: "BROOKLYN, NY",
    image: "/images/showroom1.jpeg",
    images: ["/images/showroom2.jpeg", "/images/showroom3.jpeg", "/images/showroom1.jpeg"],
imageLabels: ["SHOWROOM VIEW", "CEILING DETAIL", "FINAL LOOK"],
    objectives: [
      "120 loft units delivered",
      "Original brick facade preserved",
      "Rooftop amenity deck added",
      "Rezoning & permits secured",
    ],
    stats: { area: "210K", floors: "8", value: "$95M", completion: "88" },
    status: {
      phase: "FINISHING PHASE",
      progress: 88,
      client: "Brooklyn Realty Partners",
      architect: "ODA New York",
      structural: "Gilsanz Murray",
      startDate: "Apr 2022",
      endDate: "Jun 2025",
    },
    highlights: [
      { icon: "🏭", title: "Adaptive Reuse", desc: "Factory to luxury lofts" },
      { icon: "🧱", title: "Heritage Brick",  desc: "Original facade kept"   },
      { icon: "🌇", title: "Rooftop Deck",   desc: "Skyline amenity space"   },
    ],
    testimonial: {
      text: "Brooklyn needed this. The adaptive reuse approach preserved the soul of the old factory while creating genuinely beautiful places to live. Demand exceeded projections by 200%.",
      name: "Marcus Webb",
      role: "Partner, Brooklyn Realty",
      avatar: "https://i.pravatar.cc/80?img=7",
    },
    mapLocation: "Brooklyn, NY — DUMBO neighborhood, near Manhattan Bridge, Brooklyn waterfront.",
  },
  {
    id: 7,
    cat: "construction",
    title: "HARBOR POINT TOWER",
    desc: "A 30-story mixed-use high-rise combining offices and retail with waterfront access.",
    body: "Designed for connectivity and community, Harbor Point Tower offers premium office floors, ground-level retail, and panoramic views of Miami's iconic waterfront.",
    location: "MIAMI, FL",
    image: "/images/pool3.jpg",
    images: ["/images/pool3.jpg", "/images/apart.jpeg", "/images/gag5.jpeg", "/images/barber4.jpeg", "/images/apart2.jpeg"],
    imageLabels: ["TOWER VIEW", "LOBBY DESIGN", "STRUCTURAL CORE", "FACADE DETAIL", "WATERFRONT"],
    objectives: [
      "Mixed-use zoning approval",
      "Hurricane Cat 5 rated facade",
      "Waterfront public promenade",
      "WELL Building certification",
    ],
    stats: { area: "380K", floors: "30", value: "$210M", completion: "55" },
    status: {
      phase: "STRUCTURAL PHASE",
      progress: 55,
      client: "Harbor Dev Corp.",
      architect: "Arquitectonica",
      structural: "DeSimone Consulting",
      startDate: "Feb 2023",
      endDate: "Jan 2026",
    },
    highlights: [
      { icon: "🌊", title: "Waterfront",       desc: "Direct bay access"        },
      { icon: "🌀", title: "Hurricane Rated",  desc: "Cat 5 facade system"      },
      { icon: "🏢", title: "Mixed-Use",        desc: "Office + retail + public" },
    ],
    testimonial: {
      text: "Harbor Point will be Miami's next iconic address. The integration of public waterfront space with premium commercial floors is genuinely innovative urban design at its best.",
      name: "Rosa Mendes",
      role: "VP Development, Harbor Corp.",
      avatar: "https://i.pravatar.cc/80?img=20",
    },
    mapLocation: "Miami, FL — Brickell District, Biscayne Bay waterfront, near I-95 & US-1.",
  },
  {
    id: 8,
    cat: "renovation",
    title: "CENTRAL MARKET HALL",
    desc: "Historic market hall restored with modern steel and glass canopy over the original structure.",
    body: "A seamless fusion of old and new — the original cast-iron columns now stand beneath a sweeping glass canopy, reviving Philadelphia's busiest market as a modern public space.",
    location: "PHILADELPHIA, PA",
    image: "/images/barber.jpeg",
    images: ["/images/barber.jpeg", "/images/gag12.jpeg", "/images/gag1.jpeg", "/images/apart2.jpeg", "/images/barber4.jpeg"],
    imageLabels: ["MAIN HALL", "GLASS CANOPY", "IRON COLUMNS", "FOOD STALLS", "PLAZA VIEW"],
    objectives: [
      "Cast-iron column restoration",
      "Glass canopy installation",
      "Food hall reactivation",
      "Public plaza design",
    ],
    stats: { area: "65K", floors: "2", value: "$34M", completion: "100" },
    status: {
      phase: "COMPLETED",
      progress: 100,
      client: "Philadelphia Redevelopment",
      architect: "Robert A.M. Stern",
      structural: "Keast & Hood",
      startDate: "May 2020",
      endDate: "Oct 2022",
    },
    highlights: [
      { icon: "🏛️", title: "Historic Hall", desc: "1892 structure restored"  },
      { icon: "🪟",  title: "Glass Canopy", desc: "Modern steel + glass roof" },
      { icon: "✅",  title: "Completed",    desc: "Award-winning project"     },
    ],
    testimonial: {
      text: "This market is the heart of our neighborhood. Seeing it restored so beautifully while becoming an even better public space has meant everything to the community. Simply stunning.",
      name: "Frank Castellano",
      role: "Director, Philadelphia Redevelopment",
      avatar: "https://i.pravatar.cc/80?img=17",
    },
    mapLocation: "Philadelphia, PA — Reading Terminal area, Market St & 12th St, Center City.",
  },
  {
    id: 9,
    cat: "maintenance",
    title: "WESTSIDE OVERPASS",
    desc: "Full structural inspection and reinforcement of a critical urban highway overpass.",
    body: "A comprehensive rehabilitation project covering load testing, concrete reinforcement, and joint replacement — keeping one of LA's busiest corridors safe and operational.",
    location: "LOS ANGELES, CA",
    image: "/images/apart2nd.jpeg",
    images: ["/images/apart2nd.jpeg", "/images/gag5.jpeg", "/images/barber4.jpeg", "/images/apart.jpeg", "/images/pool3.jpg"],
    imageLabels: ["OVERPASS VIEW", "INSPECTION WORK", "JOINT REPAIR", "CONCRETE POUR", "FINAL DECK"],
    objectives: [
      "Load capacity assessment",
      "Concrete reinforcement",
      "Expansion joint replacement",
      "Zero lane closure downtime",
    ],
    stats: { area: "1.8KM", floors: "—", value: "$18M", completion: "100" },
    status: {
      phase: "COMPLETED",
      progress: 100,
      client: "LA Dept. of Transportation",
      architect: "WSP Global",
      structural: "Caltrop Corp.",
      startDate: "Jan 2023",
      endDate: "Sep 2023",
    },
    highlights: [
      { icon: "🛣️", title: "1.8KM Span",   desc: "Major urban overpass"   },
      { icon: "🔧", title: "Zero Closure",  desc: "Live traffic maintained" },
      { icon: "✅",  title: "Completed",    desc: "On time delivery"        },
    ],
    testimonial: {
      text: "Remarkably executed. Reinforcing a live highway overpass with zero lane closures during peak hours is an enormous logistical challenge. The team delivered without a single incident.",
      name: "Angela Torres",
      role: "Commissioner, LA DOT",
      avatar: "https://i.pravatar.cc/80?img=25",
    },
    mapLocation: "Los Angeles, CA — Westside, near I-10 & La Cienega Blvd interchange.",
  },
];
