export const PROJECTS_DATA = [
 {
  id: 1,
  cat: "renovation",
  title: "LAKE TERRACE RESIDENCES",
  desc: "A comprehensive residential renovation within Lake Terrace Tower Cluster D, JLT — modernizing interiors, upgrading core systems, and delivering refined living spaces suited for contemporary Dubai lifestyle.",
  body: "This residential renovation project within the prestigious Lake Terrace Tower Cluster D, JLT, Dubai, involved a full-scale transformation of the apartment unit — from flooring and wall treatments to kitchen, bathroom, and MEP system overhauls — delivering a modern, high-quality living environment.",
  location: "LAKE TERRACE TOWER CLUSTER (D), JLT, DUBAI",
  image: "/images/apt2.jpeg",
},
{
  id: 2,
  cat: "construction",
  title: "LIV MARINA MEDIA WALL",
  desc: "A precision-crafted media wall installation delivering a seamless entertainment focal point for a premium Marina residence.",
  body: "A bespoke media wall was designed and installed at Liv Residence Marina, combining clean structural joinery with integrated cable management and a refined finish — creating a striking centerpiece for modern living.",
  location: "LIV RESIDENCE, MARINA, DUBAI",
  image: "/images/wall3.jpeg",
},
 {
  id: 3,
  cat: "renovation",
  title: "LAKE TERRACE SUITE",
  desc: "A refined single-room renovation within Lake Terrace Tower Cluster D, JLT — transforming a compact space with modern finishes and smart design.",
  body: "This single-room renovation at Lake Terrace Tower Cluster D, JLT involved a complete interior overhaul — fresh wall treatments, flooring upgrade, and modern fixtures delivering a clean, contemporary living space.",
  location: "LAKE TERRACE TOWER CLUSTER (D), JLT, DUBAI",
  image: "/images/room2.jpeg",
},
 {
  id: 4,
  cat: "construction",
  title: "LIV 27 BARBERSHOP",
  desc: "A full-scale barbershop construction and interior fit-out at Media City — designed and built from scratch with a modern, premium aesthetic.",
  body: "Liv 27 Barbershop at Media City was built entirely from the ground up — covering spatial planning, joinery, lighting design, plumbing, electrical works, and complete interior fit-out to deliver a fully operational premium barbershop.",
  location: "LIV 27, MEDIA CITY, DUBAI",
  image: "/images/bar1.jpeg",
},
{
  id: 5,
  cat: "maintenance",
  title: "LVM CEILING LED INSTALL",
  desc: "Professional ceiling hanging LED lights installation across a premium performance car rental showroom in Al Quoz — enhancing ambiance and vehicle display lighting.",
  body: "A complete ceiling LED lighting solution was designed and installed at LVM Performance Car Rental, Al Quoz — covering hanging LED fixtures, wiring, and finishing to elevate the showroom's premium look and feel.",
  location: "AL QUOZ, LVM PERFORMANCE CAR RENTAL L.L.C, DUBAI",
  image: "/images/showroom1.jpeg",
},
  {
  id: 6,
  cat: "construction",
  title: "GOLD CREST VIEW 2 — JLT",
  desc: "Residential construction and fitout works at Gold Crest View 2, Cluster J, Jumeirah Lake Towers — delivering premium living spaces in the heart of Dubai.",
  body: "A full-scale residential construction and interior fitout project undertaken at Gold Crest View 2, JLT Cluster J. Works included structural upgrades, flooring, ceiling, MEP installations, and finishing — tailored to meet the high standards of JLT's premium residential community.",
  location: "GOLD CREST VIEW 2, CLUSTER J, JLT, DUBAI",
  image: "/images/apt2-3.jpeg",
},
  {
  id: 7,
  cat: "maintenance",
  title: "LIV 27 BARBER SHOP — AL BARSHA",
  desc: "Complete fitout and interior construction of a premium barber shop at Liv 27, Al Barsha 1, Dubai — delivering a sleek, modern grooming space from scratch.",
  body: "A full barber shop fitout was carried out at Liv 27, Al Barsha 1, Dubai. The project covered complete interior construction including custom barber stations, plumbing, electrical works, wall cladding, flooring, ceiling works, and all finishing — resulting in a premium modern grooming space ready for operations.",
  location: "LIV 27, AL BARSHA 1, DUBAI",
  image: "/images/barber2-2.jpeg",
},
  {
    id: 8,
    cat: "construction",
    title: "TKMMAFIT WOODEN DISPLAY",
    desc: "Custom-built premium wood display cabinet work for an elite fitness environment.",
    body: "Expertly constructed wooden display units featuring bespoke joinery and high-end finishing, integrated seamlessly into the TKMMAFIT facility in Al Barsha.",
    location: "TKMMAFIT, AL BARSHA, DUBAI",
    image: '/images/fitout.jpeg'
},
 {
    id: 9,
    cat: "maintenance",
    title: "AL BARARI LUXURY POOL CARE",
    desc: "Professional pool cleaning and maintenance work located in Al Barari.",
    body: "Expert maintenance including chemical balancing, filtration system checks, and deep cleaning for luxury residential pools in Al Barari, Dubai.",
    location: "AL BARARI, DUBAI",
    image: '/images/pool1.jpeg'
}
];